# Generated by Django 6.0.7 on 2026-09-17 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='allergies',
            field=models.TextField(blank=True, help_text='Known medical allergies'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='blood_group',
            field=models.CharField(blank=True, help_text='Blood group e.g. O+, A+', max_length=5),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='height_cm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Height in cm', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='medical_conditions',
            field=models.TextField(blank=True, help_text='Known medical conditions'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg', max_digits=5, null=True),
        ),
    ]
